# Generated by Django 5.2.8 on 2025-11-24 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("given_name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("profile_description", models.TextField(blank=True, null=True)),
                ("password", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="Caregiver",
            fields=[
                (
                    "caregiver_user",
                    models.OneToOneField(
                        db_column="caregiver_user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="caregiver_profile",
                        serialize=False,
                        to="core.user",
                    ),
                ),
                ("photo", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "caregiving_type",
                    models.CharField(
                        choices=[
                            ("Babysitter", "Babysitter"),
                            ("Elderly Care", "Elderly Care"),
                            ("Playmate", "Playmate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("hourly_rate", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                "db_table": "caregiver",
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "member_user",
                    models.OneToOneField(
                        db_column="member_user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="member_profile",
                        serialize=False,
                        to="core.user",
                    ),
                ),
                ("house_rules", models.TextField(blank=True, null=True)),
                ("dependent_description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "member",
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("job_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "required_caregiving_type",
                    models.CharField(
                        choices=[
                            ("Babysitter", "Babysitter"),
                            ("Elderly Care", "Elderly Care"),
                            ("Playmate", "Playmate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("other_requirements", models.TextField(blank=True, null=True)),
                ("date_posted", models.DateField()),
                (
                    "member",
                    models.ForeignKey(
                        db_column="member_user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="core.member",
                    ),
                ),
            ],
            options={
                "db_table": "job",
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("appointment_id", models.AutoField(primary_key=True, serialize=False)),
                ("appointment_date", models.DateField()),
                ("appointment_time", models.TimeField()),
                ("work_hours", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Declined", "Declined"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                (
                    "caregiver",
                    models.ForeignKey(
                        db_column="caregiver_user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="core.caregiver",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        db_column="member_user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="core.member",
                    ),
                ),
            ],
            options={
                "db_table": "appointment",
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_applied", models.DateField()),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="core.job",
                    ),
                ),
                (
                    "caregiver",
                    models.ForeignKey(
                        db_column="caregiver_user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to="core.caregiver",
                    ),
                ),
            ],
            options={
                "db_table": "job_application",
                "unique_together": {("caregiver", "job")},
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("house_number", models.CharField(max_length=20)),
                ("street", models.CharField(max_length=255)),
                ("town", models.CharField(max_length=100)),
                (
                    "member",
                    models.ForeignKey(
                        db_column="member_user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="core.member",
                    ),
                ),
            ],
            options={
                "db_table": "address",
                "unique_together": {("member", "house_number", "street", "town")},
            },
        ),
    ]
