# Generated by Django 5.2.7 on 2025-11-24 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='member',
            field=models.ForeignKey(db_column='member_user_id', on_delete=django.db.models.deletion.CASCADE, to='core.member'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='caregiver',
            field=models.ForeignKey(db_column='caregiver_user_id', on_delete=django.db.models.deletion.CASCADE, to='core.caregiver'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='member',
            field=models.ForeignKey(db_column='member_user_id', on_delete=django.db.models.deletion.CASCADE, to='core.member'),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='caregiver_user',
            field=models.OneToOneField(db_column='caregiver_user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.user'),
        ),
        migrations.AlterField(
            model_name='job',
            name='member',
            field=models.ForeignKey(db_column='member_user_id', on_delete=django.db.models.deletion.CASCADE, to='core.member'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='caregiver',
            field=models.ForeignKey(db_column='caregiver_user_id', on_delete=django.db.models.deletion.CASCADE, to='core.caregiver'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_user',
            field=models.OneToOneField(db_column='member_user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.user'),
        ),
    ]
